import assert from 'node:assert/strict'
import test from 'node:test'
import { normalizeWordInput } from '../src/main/database.ts'

test('规则复数转为单数', () => {
  assert.equal(normalizeWordInput('apples'), 'apple')
  assert.equal(normalizeWordInput('cats'), 'cat')
  assert.equal(normalizeWordInput('boxes'), 'box')
  assert.equal(normalizeWordInput('churches'), 'church')
  assert.equal(normalizeWordInput('wishes'), 'wish')
  assert.equal(normalizeWordInput('berries'), 'berry')
  assert.equal(normalizeWordInput('parties'), 'party')
  assert.equal(normalizeWordInput('stories'), 'story')
  assert.equal(normalizeWordInput('potatoes'), 'potato')
  assert.equal(normalizeWordInput('volcanoes'), 'volcano')
  assert.equal(normalizeWordInput('buses'), 'bus')
  assert.equal(normalizeWordInput('glasses'), 'glass')
  assert.equal(normalizeWordInput('houses'), 'house')
  assert.equal(normalizeWordInput('responses'), 'response')
  assert.equal(normalizeWordInput('viruses'), 'virus')
  assert.equal(normalizeWordInput('processes'), 'process')
})

test('-ves 结尾的复数转为单数', () => {
  assert.equal(normalizeWordInput('leaves'), 'leaf')
  assert.equal(normalizeWordInput('knives'), 'knife')
  assert.equal(normalizeWordInput('wives'), 'wife')
  assert.equal(normalizeWordInput('lives'), 'life')
  assert.equal(normalizeWordInput('wolves'), 'wolf')
  assert.equal(normalizeWordInput('shelves'), 'shelf')
  assert.equal(normalizeWordInput('loaves'), 'loaf')
  assert.equal(normalizeWordInput('hooves'), 'hoof')
  assert.equal(normalizeWordInput('caves'), 'cave')
  assert.equal(normalizeWordInput('hives'), 'hive')
})

test('不规则复数转为单数', () => {
  assert.equal(normalizeWordInput('children'), 'child')
  assert.equal(normalizeWordInput('men'), 'man')
  assert.equal(normalizeWordInput('women'), 'woman')
  assert.equal(normalizeWordInput('feet'), 'foot')
  assert.equal(normalizeWordInput('teeth'), 'tooth')
  assert.equal(normalizeWordInput('mice'), 'mouse')
  assert.equal(normalizeWordInput('geese'), 'goose')
  assert.equal(normalizeWordInput('people'), 'person')
  assert.equal(normalizeWordInput('oxen'), 'ox')
  assert.equal(normalizeWordInput('dice'), 'die')
  assert.equal(normalizeWordInput('lice'), 'louse')
  assert.equal(normalizeWordInput('analyses'), 'analysis')
  assert.equal(normalizeWordInput('crises'), 'crisis')
  assert.equal(normalizeWordInput('theses'), 'thesis')
  assert.equal(normalizeWordInput('criteria'), 'criterion')
  assert.equal(normalizeWordInput('phenomena'), 'phenomenon')
  assert.equal(normalizeWordInput('indices'), 'index')
  assert.equal(normalizeWordInput('matrices'), 'matrix')
  assert.equal(normalizeWordInput('vertices'), 'vertex')
})

test('已是单数或不可数名词保持不变', () => {
  assert.equal(normalizeWordInput('bus'), 'bus')
  assert.equal(normalizeWordInput('analysis'), 'analysis')
  assert.equal(normalizeWordInput('sheep'), 'sheep')
  assert.equal(normalizeWordInput('fish'), 'fish')
  assert.equal(normalizeWordInput('news'), 'news')
  assert.equal(normalizeWordInput('series'), 'series')
  assert.equal(normalizeWordInput('status'), 'status')
  assert.equal(normalizeWordInput('focus'), 'focus')
  assert.equal(normalizeWordInput('cactus'), 'cactus')
})

test('复数规则之外的常见误判被修正', () => {
  assert.equal(normalizeWordInput('cookies'), 'cookie')
  assert.equal(normalizeWordInput('calories'), 'calorie')
  assert.equal(normalizeWordInput('brownies'), 'brownie')
  assert.equal(normalizeWordInput('selfies'), 'selfie')
  assert.equal(normalizeWordInput('movies'), 'movie')
  assert.equal(normalizeWordInput('ties'), 'tie')
  assert.equal(normalizeWordInput('zombies'), 'zombie')
  assert.equal(normalizeWordInput('physics'), 'physics')
  assert.equal(normalizeWordInput('mathematics'), 'mathematics')
  assert.equal(normalizeWordInput('economics'), 'economics')
  assert.equal(normalizeWordInput('data'), 'data')
  assert.equal(normalizeWordInput('media'), 'media')
})

test('去除首尾与多余空格后再转单数', () => {
  assert.equal(normalizeWordInput('  apples  '), 'apple')
  assert.equal(normalizeWordInput('apple   '), 'apple')
  assert.equal(normalizeWordInput('\tApples\n'), 'apple')
})

test('多词短语保留内部空格', () => {
  assert.equal(normalizeWordInput('apple  juice'), 'apple juice')
  assert.equal(normalizeWordInput('ad hoc'), 'ad hoc')
})

test('默认转小写，专有名词保留大小写', () => {
  assert.equal(normalizeWordInput('Apples'), 'apple')
  assert.equal(normalizeWordInput('CATS'), 'cat')
  assert.equal(normalizeWordInput('Women'), 'woman')
  assert.equal(normalizeWordInput('Physics'), 'physics')
  assert.equal(normalizeWordInput('China'), 'China')
  assert.equal(normalizeWordInput('china'), 'china')
  assert.equal(normalizeWordInput('English'), 'English')
  assert.equal(normalizeWordInput('Americans'), 'American')
  assert.equal(normalizeWordInput('Philippines'), 'Philippines')
  assert.equal(normalizeWordInput('Paris'), 'Paris')
  assert.equal(normalizeWordInput('March'), 'March')
  assert.equal(normalizeWordInput('Monday'), 'Monday')
})
